# Default settings for C++
compilers=&gcc:&clang
group.gcc.compilerCategories=gcc
group.clang.intelAsm=-mllvm --x86-asm-syntax=intel
group.clang.compilerType=clang
group.clang.compilerCategories=clang

defaultCompiler=clang22
postProcess=
demangler=c++filt
demanglerType=cpp
objdumper=objdump
options=
supportsBinary=true
supportsBinaryObject=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*|_dl_relocate_static_pie)$
needsMulti=false
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
supportsLibraryCodeFilter=true
